name = "scheduler"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[[d1_databases]]
binding = "DB"
database_name = "scheduler_db"
database_id ="b6a4ecef-ac0c-4d0d-80ea-4998813da150"
migrations_dir = "migrations"

[durable_objects]
bindings = [
  { name = "DO_SCHEDULER", class_name = "Scheduler" }
]

[[migrations]]
tag = "v1"
new_classes = ["Scheduler"]